# Generated by Django 3.2.21 on 2023-10-26 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0197_org_slugs_begin_with_letter'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE judge_submission 
            SET time = (
                SELECT MAX(stc.time) 
                FROM judge_submissiontestcase stc 
                WHERE stc.submission_id = judge_submission.id
            )
            """,
            """
            UPDATE judge_submission 
            SET time = (
                SELECT SUM(stc.time) 
                FROM judge_submissiontestcase stc 
                WHERE stc.submission_id = judge_submission.id
            )
            """,
        ),
    ]